// !!!!!!!!!!!!!!!!!!!!!!!!!!!! products data  !!!!!!!!!!!!!!!!!!!!!!


/*
  in this fille we have all data of our products and Categories

*/
// ======================= products data  ========================


//  = [
//     {
//       id:0,
//       name: "Mangosteen Organic from Vietnamseo",
//       category: "Fresh Fruits",
//       priceBeforeDiscount: 88,
//       priceAfterDiscount: 43,
//       rating: 4.5,
//       src: "assets/storeimge/stor (0).jpeg",
//       src2: "assets/storeimge/stor (1).jpeg",
//       des1:`Delicious Non-Dairy cheese sauce`,
//       des2:`Vegan & Allergy Friendly`,
//       des3:`Smooth, velvety Dairy free cheese sauce`,

//     },
//     {
//       id:1,
//       name: "Soda Sparkling Water Maker (Rose Gold)",
//       category: "Fresh Fruits",
//       priceBeforeDiscount: 80,
//       priceAfterDiscount: 70,
//       rating: 5,
//       src: "assets/storeimge/stor (2).jpeg",   
//       src2: "assets/storeimge/stor (3).jpeg",
//       des1:`Delicious Non-Dairy cheese sauce`,
//       des2:`Vegan & Allergy Friendly`,
//       des3:`Smooth, velvety Dairy free cheese sauce`,
//     },
  
//     {
//       id:2,
//       name: "HOT - Lettuce Fresh Produce Fruit Vegetables",
//       category: "Vegetables",
//       priceBeforeDiscount: 112,
//       priceAfterDiscount: 56,
//       rating: 2,
//       src: "assets/storeimge/stor (4).jpeg",
//       src2: "assets/storeimge/stor (5).jpeg",
//       des1:`Delicious Non-Dairy cheese sauce`,
//       des2:`Vegan & Allergy Friendly`,
//       des3:`Smooth, velvety Dairy free cheese sauce`,
//     },
 
//     {
//       id:3,
//       name: "Luffy Taffy Lift Bites Gone Bananas - 4 Packs",
//       category: "Fresh Fruits",
//       priceBeforeDiscount: 155,
//       priceAfterDiscount: 56,
//       rating: 3.3,
//       src: "assets/storeimge/stor (6).jpeg",
//       src2: "assets/storeimge/stor (7).jpeg",
//       des1:`Delicious Non-Dairy cheese sauce`,
//       des2:`Vegan & Allergy Friendly`,
//       des3:`Smooth, velvety Dairy free cheese sauce`,
//     },
   
//     {
//       id:4,
//       name: "Pure Irish Organic Beef Quarter Pounder Burgers",
//       category: "Fresh Meat",
//       priceBeforeDiscount: 90,
//       priceAfterDiscount: 80,
//       rating: 5,
//       src: "assets/storeimge/stor (8).jpeg",
//       src2: "assets/storeimge/stor (9).jpeg",
//       des1:`Delicious Non-Dairy cheese sauce`,
//       des2:`Vegan & Allergy Friendly`,
//       des3:`Smooth, velvety Dairy free cheese sauce`,
//     },
 
//     {
//       id:5,
//       name: "Ginger Fresh, Whole, Organic - 250gram",
//       category: "Vegetables",
//       priceBeforeDiscount: 45,
//       priceAfterDiscount: 18,
//       rating: 4.8,
//       src: "assets/storeimge/stor (10).jpeg",
//       src2: "assets/storeimge/stor (11).jpeg",
//       des1:`Delicious Non-Dairy cheese sauce`,
//       des2:`Vegan & Allergy Friendly`,
//       des3:`Smooth, velvety Dairy free cheese sauce`,
//     },
//     {
//       id:6,
//       name: "HOT - Chicken Fresh from Vietnamseo",
//       category: "Fresh Meat",
//       priceBeforeDiscount: 200,
//       priceAfterDiscount: 156,
//       rating:5,
//       src: "assets/storeimge/stor (12).jpeg",
//       src2: "assets/storeimge/stor (13).jpeg",
//       des1:`Delicious Non-Dairy cheese sauce`,
//       des2:`Vegan & Allergy Friendly`,
//       des3:`Smooth, velvety Dairy free cheese sauce`,
//     },
//     {
//       id:7,
//       name: "Soda Sparkling Water Maker (Rose Gold)",
//       category: "Fresh Meat",
//       priceBeforeDiscount: 130,
//       priceAfterDiscount: 76,
//       rating: 3.9,
//       src: "assets/storeimge/stor (14).jpeg",
//       src2: "assets/storeimge/stor (15).jpeg",
//       des1:`Delicious Non-Dairy cheese sauce`,
//       des2:`Vegan & Allergy Friendly`,
//       des3:`Smooth, velvety Dairy free cheese sauce`,
//     },
//     {
//       id:8,
//       name: "Mangosteen Organic from Vietnamseo",
//       category: "Fresh Fruits",
//       priceBeforeDiscount: 55,
//       priceAfterDiscount: 38,
//       rating: 4.7,
//       src: "assets/storeimge/stor (16).jpeg",
//       src2: "assets/storeimge/stor (17).jpeg",
//       des1:`Delicious Non-Dairy cheese sauce`,
//       des2:`Vegan & Allergy Friendly`,
//       des3:`Smooth, velvety Dairy free cheese sauce`,
//     },
//     { 
//       id: 9, 
//       name: "Fresh Organic Blueberries", 
//       category: "Fresh Fruits", 
//       priceBeforeDiscount: 100, 
//       priceAfterDiscount: 75, 
//       rating: 4.5, 
//       src: "assets/storeimge/stor (18).jpeg", 
//       src2: "assets/storeimge/stor (19).jpeg", 
//       des1: "Delicious Non-Dairy cheese sauce", 
//       des2: "Vegan & Allergy Friendly", 
//       des3: "Smooth, velvety Dairy free cheese sauce" 
//     },
//     { 
//       id: 10, 
//       name: "Dried Natural Blueberries", 
//       category: "Fresh Fruits", 
//       priceBeforeDiscount: 90, 
//       priceAfterDiscount: 60, 
//       rating: 3.8, 
//       src: "assets/storeimge/stor (20).jpeg", 
//       src2: "assets/storeimge/stor (21).jpeg", 
//       des1: "Delicious Non-Dairy cheese sauce", 
//       des2: "Vegan & Allergy Friendly", 
//       des3: "Smooth, velvety Dairy free cheese sauce" 
//     },
//     { 
//       id: 11, 
//       name: "Golden Premium Raisins", 
//       category: "Biscuits Snack", 
//       priceBeforeDiscount: 50, 
//       priceAfterDiscount: 25, 
//       rating: 4.2, 
//       src: "assets/storeimge/stor (22).jpeg", 
//       src2: "assets/storeimge/stor (23).jpeg", 
//       des1: "Delicious Non-Dairy cheese sauce", 
//       des2: "Vegan & Allergy Friendly", 
//       des3: "Smooth, velvety Dairy free cheese sauce" 
//     },
//     { 
//       id: 12, 
//       name: "Brown Sweet Raisins", 
//       category: "Biscuits Snack", 
//       priceBeforeDiscount: 40, 
//       priceAfterDiscount: 20, 
//       rating: 3.5, 
//       src: "assets/storeimge/stor (24).jpeg", 
//       src2: "assets/storeimge/stor (25).jpeg", 
//       des1: "Delicious Non-Dairy cheese sauce", 
//       des2: "Vegan & Allergy Friendly", 
//       des3: "Smooth, velvety Dairy free cheese sauce" 
//     },
//     { 
//       id: 13, 
//       name: "Almonds with Green Leaves", 
//       category: "Biscuits Snack", 
//       priceBeforeDiscount: 150, 
//       priceAfterDiscount: 120, 
//       rating: 4.7, 
//       src: "assets/storeimge/stor (26).jpeg", 
//       src2: "assets/storeimge/stor (27).jpeg", 
//       des1: "Delicious Non-Dairy cheese sauce", 
//       des2: "Vegan & Allergy Friendly", 
//       des3: "Smooth, velvety Dairy free cheese sauce" 
//     },
//     { 
//       id: 14, 
//       name: "Raw Natural Almonds", 
//       category: "Biscuits Snack", 
//       priceBeforeDiscount: 140, 
//       priceAfterDiscount: 100, 
//       rating: 3.9, 
//       src: "assets/storeimge/stor (28).jpeg", 
//       src2: "assets/storeimge/stor (29).jpeg", 
//       des1: "Delicious Non-Dairy cheese sauce", 
//       des2: "Vegan & Allergy Friendly", 
//       des3: "Smooth, velvety Dairy free cheese sauce" 
//     },
//     { 
//       id: 15, 
//       name: "Black Jumbo Raisins", 
//       category: "Biscuits Snack", 
//       priceBeforeDiscount: 60, 
//       priceAfterDiscount: 45, 
//       rating: 4.0, 
//       src: "assets/storeimge/stor (30).jpeg", 
//       src2: "assets/storeimge/stor (31).jpeg", 
//       des1: "Delicious Non-Dairy cheese sauce", 
//       des2: "Vegan & Allergy Friendly", 
//       des3: "Smooth, velvety Dairy free cheese sauce" 
//     },
//     { 
//       id: 16, 
//       name: "Crunchy Fresh Pistachios", 
//       category: "Biscuits Snack", 
//       priceBeforeDiscount: 200, 
//       priceAfterDiscount: 150, 
//       rating: 4.8, 
//       src: "assets/storeimge/stor (32).jpeg", 
//       src2: "assets/storeimge/stor (33).jpeg", 
//       des1: "Delicious Non-Dairy cheese sauce", 
//       des2: "Vegan & Allergy Friendly", 
//       des3: "Smooth, velvety Dairy free cheese sauce" 
//     },
//     { 
//       id: 17, 
//       name: "Deluxe Mixed Nuts Box", 
//       category: "Biscuits Snack", 
//       priceBeforeDiscount: 250, 
//       priceAfterDiscount: 180, 
//       rating: 4.3, 
//       src: "assets/storeimge/stor (34).jpeg", 
//       src2: "assets/storeimge/stor (35).jpeg", 
//       des1: "Delicious Non-Dairy cheese sauce", 
//       des2: "Vegan & Allergy Friendly", 
//       des3: "Smooth, velvety Dairy free cheese sauce" 
//     }
 

//   ];
export const Products= [
  {
    id: 1,
    name: "Fresh Lychee Fruit",
    category: "Fresh Fruits",
    priceBeforeDiscount: 100,
    priceAfterDiscount: 50,
    src: "assets/storeimge/stor (0).jpeg",
    src2: "assets/storeimge/stor (1).jpeg",
    rating: 3.5,
    des1: `Delicious Non-Dairy cheese sauce`,
    des2: `Vegan & Allergy Friendly`,
    des3: `Smooth, velvety Dairy free cheese sauce`,
  },
  {
    id: 2,
    name: "Juicy Red Strawberries",
    category: "Fresh Fruits",
    priceBeforeDiscount: 120,
    priceAfterDiscount: 60,
    src: "assets/storeimge/stor (2).jpeg",
    src2: "assets/storeimge/stor (3).jpeg",
    rating: 4.2,
    des1: `Delicious Non-Dairy cheese sauce`,
    des2: `Vegan & Allergy Friendly`,
    des3: `Smooth, velvety Dairy free cheese sauce`,
  },
  {
    id: 3,
    name: "Green Seedless Grapes",
    category: "Fresh Fruits",
    priceBeforeDiscount: 90,
    priceAfterDiscount: 70,
    src: "assets/storeimge/stor (4).jpeg",
    src2: "assets/storeimge/stor (5).jpeg",
    rating: 3.8,
    des1: `Delicious Non-Dairy cheese sauce`,
    des2: `Vegan & Allergy Friendly`,
    des3: `Smooth, velvety Dairy free cheese sauce`,
  },
  {
    id: 4,
    name: "Organic Green Broccoli",
    category: "Vegetables",
    priceBeforeDiscount: 110,
    priceAfterDiscount: 55,
    src: "assets/storeimge/stor (6).jpeg",
    src2: "assets/storeimge/stor (7).jpeg",
    rating: 4.5,
    des1: `Delicious Non-Dairy cheese sauce`,
    des2: `Vegan & Allergy Friendly`,
    des3: `Smooth, velvety Dairy free cheese sauce`,
  },
  {
    id: 5,
    name: "Exotic Dragon Fruit",
    category: "Fresh Fruits",
    priceBeforeDiscount: 150,
    priceAfterDiscount: 75,
    src: "assets/storeimge/stor (8).jpeg",
    src2: "assets/storeimge/stor (9).jpeg",
    rating: 4.7,
    des1: `Delicious Non-Dairy cheese sauce`,
    des2: `Vegan & Allergy Friendly`,
    des3: `Smooth, velvety Dairy free cheese sauce`,
  },
  {
    id: 6,
    name: "Fresh Yellow Lemons",
    category: "Vegetables",
    priceBeforeDiscount: 80,
    priceAfterDiscount: 40,
    src: "assets/storeimge/stor (10).jpeg",
    src2: "assets/storeimge/stor (11).jpeg",
    rating: 3.9,
    des1: `Delicious Non-Dairy cheese sauce`,
    des2: `Vegan & Allergy Friendly`,
    des3: `Smooth, velvety Dairy free cheese sauce`,
  },
  // {
  //   id: 7,
  //   name: "Organic Green Broccoli",
  //   category: "Fresh Meat",
  //   priceBeforeDiscount: 50,
  //   priceAfterDiscount: 40,
  //   src: "assets/storeimge/stor (12).jpeg",
  //   src2: "assets/storeimge/stor (13).jpeg",
  //   rating: 3.6,
  //   des1: `Delicious Non-Dairy cheese sauce`,
  //   des2: `Vegan & Allergy Friendly`,
  //   des3: `Smooth, velvety Dairy free cheese sauce`,
  // },
  // {
  //   id: 8,
  //   name: "Fresh White Cauliflower",
  //   category: "Fresh Meat",
  //   priceBeforeDiscount: 60,
  //   priceAfterDiscount: 30,
  //   src: "assets/storeimge/stor (14).jpeg",
  //   src2: "assets/storeimge/stor (15).jpeg",
  //   rating: 4.3,
  //   des1: `Delicious Non-Dairy cheese sauce`,
  //   des2: `Vegan & Allergy Friendly`,
  //   des3: `Smooth, velvety Dairy free cheese sauce`,
  // },
  {
    id: 9,
    name: "Fresh Mangosteen Fruit",
    category: "Fresh Fruits",
    priceBeforeDiscount: 200,
    priceAfterDiscount: 80,
    src: "assets/storeimge/stor (16).jpeg",
    src2: "assets/storeimge/stor (17).jpeg",
    rating: 4.9,
    des1: `Delicious Non-Dairy cheese sauce`,
    des2: `Vegan & Allergy Friendly`,
    des3: `Smooth, velvety Dairy free cheese sauce`,
  },
  {
    id: 10,
    name: "Fresh Ginger Root",
    category: "Vegetables",
    priceBeforeDiscount: 40,
    priceAfterDiscount: 20,
    src: "assets/storeimge/stor (18).jpeg",
    src2: "assets/storeimge/stor (19).jpeg",
    rating: 3.2,
    des1: `Delicious Non-Dairy cheese sauce`,
    des2: `Vegan & Allergy Friendly`,
    des3: `Smooth, velvety Dairy free cheese sauce`,
  },
  {
    id: 11,
    name: "Golden Raisins",
    category: "Snacks",
    priceBeforeDiscount: 50,
    priceAfterDiscount: 25,
    src: "assets/storeimge/stor (20).jpeg",
    src2: "assets/storeimge/stor (21).jpeg",
    rating: 3.7,
    des1: `Delicious Non-Dairy cheese sauce`,
    des2: `Vegan & Allergy Friendly`,
    des3: `Smooth, velvety Dairy free cheese sauce`,
  },
  {
    id: 12,
    name: "Whole Organic Almonds",
    category: "Snacks",
    priceBeforeDiscount: 180,
    priceAfterDiscount: 120,
    src: "assets/storeimge/stor (22).jpeg",
    src2: "assets/storeimge/stor (23).jpeg",
    rating: 4.4,
    des1: `Delicious Non-Dairy cheese sauce`,
    des2: `Vegan & Allergy Friendly`,
    des3: `Smooth, velvety Dairy free cheese sauce`,
  },
  {
    id: 13,
    name: "Black Raisins",
    category: "Snacks",
    priceBeforeDiscount: 100,
    priceAfterDiscount: 50,
    src: "assets/storeimge/stor (24).jpeg",
    src2: "assets/storeimge/stor (25).jpeg",
    rating: 3.8,
    des1: `Delicious Non-Dairy cheese sauce`,
    des2: `Vegan & Allergy Friendly`,
    des3: `Smooth, velvety Dairy free cheese sauce`,
  },
  {
    id: 14,
    name: "Pistachio Nuts",
    category: "Snacks",
    priceBeforeDiscount: 200,
    priceAfterDiscount: 100,
    src: "assets/storeimge/stor (26).jpeg",
    src2: "assets/storeimge/stor (27).jpeg",
    rating: 4.1,
    des1: `Delicious Non-Dairy cheese sauce`,
    des2: `Vegan & Allergy Friendly`,
    des3: `Smooth, velvety Dairy free cheese sauce`,
  },
  {
    id: 15,
    name: "Organic Walnut Halves",
    category: "Snacks",
    priceBeforeDiscount: 220,
    priceAfterDiscount: 110,
    src: "assets/storeimge/stor (28).jpeg",
    src2: "assets/storeimge/stor (29).jpeg",
    rating: 3.6,
    des1: `Delicious Non-Dairy cheese sauce`,
    des2: `Vegan & Allergy Friendly`,
    des3: `Smooth, velvety Dairy free cheese sauce`,
  },
  {
    id: 16,
    name: "Dried Turkish Figs",
    category: "Snacks",
    priceBeforeDiscount: 300,
    priceAfterDiscount: 140,
    src: "assets/storeimge/stor (30).jpeg",
    src2: "assets/storeimge/stor (31).jpeg",
    rating: 4.8,
    des1: `Delicious Non-Dairy cheese sauce`,
    des2: `Vegan & Allergy Friendly`,
    des3: `Smooth, velvety Dairy free cheese sauce`,
  },
  {
    id: 17,
    name: "Fresh Blueberries",
    category: "Fresh Fruits",
    priceBeforeDiscount: 60,
    priceAfterDiscount: 30,
    src: "assets/storeimge/stor (32).jpeg",
    src2: "assets/storeimge/stor (33).jpeg",
    rating: 4.6,
    des1: `Delicious Non-Dairy cheese sauce`,
    des2: `Vegan & Allergy Friendly`,
    des3: `Smooth, velvety Dairy free cheese sauce`,
  },
  {
    id: 18,
    name: "Fresh Yellow Onions",
    category: "Vegetables",
    priceBeforeDiscount: 20,
    priceAfterDiscount: 15,
    src: "assets/storeimge/stor (34).jpeg",
    src2: "assets/storeimge/stor (35).jpeg",
    rating: 3.3,
    des1: `Delicious Non-Dairy cheese sauce`,
    des2: `Vegan & Allergy Friendly`,
    des3: `Smooth, velvety Dairy free cheese sauce`,
  },
  {
    id: 19,
    name: "Sweet Juicy Carrots",
    category: "Vegetables",
    priceBeforeDiscount: 30,
    priceAfterDiscount: 20,
    src: "assets/storeimge/stor (36).jpeg",
    src2: "assets/storeimge/stor (37).jpeg",
    rating: 3.7,
    des1: `Delicious Non-Dairy cheese sauce`,
    des2: `Vegan & Allergy Friendly`,
    des3: `Smooth, velvety Dairy free cheese sauce`,
  },
  {
    id: 20,
    name: "Fresh Yellow Bananas",
    category: "Fresh Fruits",
    priceBeforeDiscount: 60,
    priceAfterDiscount: 40,
    src: "assets/storeimge/stor (38).jpeg",
    src2: "assets/storeimge/stor (39).jpeg",
    rating: 4.2,
    des1: `Delicious Non-Dairy cheese sauce`,
    des2: `Vegan & Allergy Friendly`,
    des3: `Smooth, velvety Dairy free cheese sauce`,
  },
  {
    id: 21,
    name: "Crunchy Red Apples",
    category: "Fresh Fruits",
    priceBeforeDiscount: 70,
    priceAfterDiscount: 50,
    src: "assets/storeimge/stor (40).jpeg",
    src2: "assets/storeimge/stor (41).jpeg",
    rating: 3.9,
    des1: `Delicious Non-Dairy cheese sauce`,
    des2: `Vegan & Allergy Friendly`,
    des3: `Smooth, velvety Dairy free cheese sauce`,
  },
  {
    id: 22,
    name: "Ripe Fresh Papayas",
    category: "Fresh Fruits",
    priceBeforeDiscount: 100,
    priceAfterDiscount: 75,
    src: "assets/storeimge/stor (42).jpeg",
    src2: "assets/storeimge/stor (43).jpeg",
    rating: 4.1,
    des1: `Delicious Non-Dairy cheese sauce`,
    des2: `Vegan & Allergy Friendly`,
    des3: `Smooth, velvety Dairy free cheese sauce`,
  },
  {
    id: 23,
    name: "Fresh Watermelon Slices",
    category: "Fresh Fruits",
    priceBeforeDiscount: 90,
    priceAfterDiscount: 45,
    src: "assets/storeimge/stor (44).jpeg",
    src2: "assets/storeimge/stor (45).jpeg",
    rating: 3.4,
    des1: `Delicious Non-Dairy cheese sauce`,
    des2: `Vegan & Allergy Friendly`,
    des3: `Smooth, velvety Dairy free cheese sauce`,
  },
  {
    id: 24,
    name: "Tropical Pineapples",
    category: "Snacks",
    priceBeforeDiscount: 120,
    priceAfterDiscount: 80,
    src: "assets/storeimge/stor (46).jpeg",
    src2: "assets/storeimge/stor (47).jpeg",
    rating: 4.5,
    des1: `Delicious Non-Dairy cheese sauce`,
    des2: `Vegan & Allergy Friendly`,
    des3: `Smooth, velvety Dairy free cheese sauce`,
  },
  // {
  //   id: 25,
  //   name: "Ripe Green Pears",
  //   category: "Fresh Fruits",
  //   priceBeforeDiscount: 60,
  //   priceAfterDiscount: 30,
  //   src: "assets/storeimge/stor (48).jpeg",
  //   src2: "assets/storeimge/stor (49).jpeg",
  //   rating: 3.2,
  //   des1: `Delicious Non-Dairy cheese sauce`,
  //   des2: `Vegan & Allergy Friendly`,
  //   des3: `Smooth, velvety Dairy free cheese sauce`,
  // },
  {
    id: 26,
    name: "Fresh Red Bell Peppers",
    category: "Snacks",
    priceBeforeDiscount: 50,
    priceAfterDiscount: 35,
    src: "assets/storeimge/stor (50).jpeg",
    src2: "assets/storeimge/stor (51).jpeg",
    rating: 4.6,
    des1: `Delicious Non-Dairy cheese sauce`,
    des2: `Vegan & Allergy Friendly`,
    des3: `Smooth, velvety Dairy free cheese sauce`,
  },
  {
    id: 27,
    name: "Crunchy Fresh Lettuce",
    category: "Vegetables",
    priceBeforeDiscount: 25,
    priceAfterDiscount: 15,
    src: "assets/storeimge/stor (52).jpeg",
    src2: "assets/storeimge/stor (53).jpeg",
    rating: 3.8,
    des1: `Delicious Non-Dairy cheese sauce`,
    des2: `Vegan & Allergy Friendly`,
    des3: `Smooth, velvety Dairy free cheese sauce`,
  },
  {
    id: 28,
    name: "Organic Spinach Leaves",
    category: "Vegetables",
    priceBeforeDiscount: 40,
    priceAfterDiscount: 20,
    src: "assets/storeimge/stor (54).jpeg",
    src2: "assets/storeimge/stor (55).jpeg",
    rating: 3.5,
    des1: `Delicious Non-Dairy cheese sauce`,
    des2: `Vegan & Allergy Friendly`,
    des3: `Smooth, velvety Dairy free cheese sauce`,
  },
  {
    id: 29,
    name: "Tasty Fresh Oranges",
    category: "Snacks",
    priceBeforeDiscount: 70,
    priceAfterDiscount: 40,
    src: "assets/storeimge/stor (56).jpeg",
    src2: "assets/storeimge/stor (57).jpeg",
    rating: 4.2,
    des1: `Delicious Non-Dairy cheese sauce`,
    des2: `Vegan & Allergy Friendly`,
    des3: `Smooth, velvety Dairy free cheese sauce`,
  },
  {
    id: 30,
    name: "Almonds with Green Leaves",
    category: "Fresh Fruits",
    priceBeforeDiscount: 200,
    priceAfterDiscount: 100,
    src: "assets/storeimge/stor (58).jpeg",
    src2: "assets/storeimge/stor (59).jpeg",
    rating: 4,
    des1: `Delicious Non-Dairy cheese sauce`,
    des2: `Vegan & Allergy Friendly`,
    des3: `Smooth, velvety Dairy free cheese sauce`,
  }
]




  // ======================= Categories data  ========================

  export const Categories = [

    {
      name: "Vegetables",
      image: "/assets/categores/category (11).jpeg",
    },
    {
      name: "Fresh Fruits",
      image: "/assets/categores/category (12).jpeg",
    },
    {
      name: "Fruit Drink",
      image: "/assets/categores/category (13).jpeg",
    },
    {
      name: "Fresh Bakery",
      image: "/assets/categores/category (14).jpeg",
    },
    {
      name: "Fresh Meat",
      image: "/assets/categores/category (16).jpeg",
    },
    {
      name: "Snacks",
      image: "/assets/categores/category (15).jpeg",
    },
    {
      name: "Fresh Milk",
      image: "/assets/categores/category (17).jpeg",
    },
  

  ];
  

  export const Products2 = [
    {
      name: "Mangosteen Organic from Vietnamseo",
      category: "Fresh Fruits",
      priceBeforeDiscount: 90,
      priceAfterDiscount: 56,
      rating: 4.5,
      src: "assets/storeimge/stor (0).jpeg",
    },
    {
      name: "Mangosteen Organic from Vietnamseo",
      category: "Fresh Fruits",
      priceBeforeDiscount: 90,
      priceAfterDiscount: 56,
      rating: 4.5,
      src: "assets/storeimge/stor (1).jpeg",
    },
    {
      name: "Soda Sparkling Water Maker (Rose Gold)",
      category: "Fresh Fruits",
      priceBeforeDiscount: 90,
      priceAfterDiscount: 56,
      rating: 4.7,
      src: "assets/storeimge/stor (2).jpeg",
    },
    {
      name: "Soda Sparkling Water Maker (Rose Gold)",
      category: "Fresh Fruits",
      priceBeforeDiscount: 90,
      priceAfterDiscount: 56,
      rating: 4.7,
      src: "assets/storeimge/stor (3).jpeg",
    },
    {
      name: "HOT - Lettuce Fresh Produce Fruit Vegetables",
      category: "Vegetables",
      priceBeforeDiscount: 90,
      priceAfterDiscount: 56,
      rating: 4.6,
      src: "assets/storeimge/stor (4).jpeg",
    },
    {
      name: "HOT - Lettuce Fresh Produce Fruit Vegetables",
      category: "Vegetables",
      priceBeforeDiscount: 90,
      priceAfterDiscount: 56,
      rating: 4.6,
      src: "assets/storeimge/stor (5).jpeg",
    },
    {
      name: "Luffy Taffy Lift Bites Gone Bananas - 4 Packs",
      category: "Fresh Fruits",
      priceBeforeDiscount: 90,
      priceAfterDiscount: 56,
      rating: 4.4,
      src: "assets/storeimge/stor (6).jpeg",
    },
    {
      name: "Luffy Taffy Lift Bites Gone Bananas - 4 Packs",
      category: "Fresh Fruits",
      priceBeforeDiscount: 90,
      priceAfterDiscount: 56,
      rating: 4.4,
      src: "assets/storeimge/stor (7).jpeg",
    },
    {
      name: "Pure Irish Organic Beef Quarter Pounder Burgers",
      category: "Fresh Meat",
      priceBeforeDiscount: 90,
      priceAfterDiscount: 56,
      rating: 4.3,
      src: "assets/storeimge/stor (8).jpeg",
    },
    {
      name: "Pure Irish Organic Beef Quarter Pounder Burgers",
      category: "Fresh Meat",
      priceBeforeDiscount: 90,
      priceAfterDiscount: 56,
      rating: 4.3,
      src: "assets/storeimge/stor (9).jpeg",
    },
    {
      name: "Ginger Fresh, Whole, Organic - 250gram",
      category: "Vegetables",
      priceBeforeDiscount: 90,
      priceAfterDiscount: 56,
      rating: 4.8,
      src: "assets/storeimge/stor (10).jpeg",
    },
    {
      name: "Ginger Fresh, Whole, Organic - 250gram",
      category: "Vegetables",
      priceBeforeDiscount: 90,
      priceAfterDiscount: 56,
      rating: 4.8,
      src: "assets/storeimge/stor (11).jpeg",
    },
    {
      name: "HOT - Chicken Fresh from Vietnamseo",
      category: "Fresh Meat",
      priceBeforeDiscount: 90,
      priceAfterDiscount: 56,
      rating: 4.6,
      src: "assets/storeimge/stor (12).jpeg",
    },
    {
      name: "HOT - Chicken Fresh from Vietnamseo",
      category: "Fresh Meat",
      priceBeforeDiscount: 90,
      priceAfterDiscount: 56,
      rating: 4.6,
      src: "assets/storeimge/stor (13).jpeg",
    },
    {
      name: "Soda Sparkling Water Maker (Rose Gold)",
      category: "Fresh Meat",
      priceBeforeDiscount: 90,
      priceAfterDiscount: 56,
      rating: 4.9,
      src: "assets/storeimge/stor (14).jpeg",
    },
    {
      name: "Soda Sparkling Water Maker (Rose Gold)",
      category: "Fresh Meat",
      priceBeforeDiscount: 90,
      priceAfterDiscount: 56,
      rating: 4.9,
      src: "assets/storeimge/stor (15).jpeg",
    },
    {
      name: "Mangosteen Organic from Vietnamseo",
      category: "Fresh Fruits",
      priceBeforeDiscount: 90,
      priceAfterDiscount: 56,
      rating: 4.7,
      src: "assets/storeimge/stor (16).jpeg",
    },
    {
      name: "HOT - Lettuce Fresh Produce Fruit Vegetables",
      category: "Vegetables",
      priceBeforeDiscount: 90,
      priceAfterDiscount: 56,
      rating: 4.3,
      src: "assets/storeimge/stor (17).jpeg",
    },
  ];





  // ======================= blogs =====================

  export const Articles = [
    {
      id: 1,
      category: "Organics",
      author: "Admin",
      date: "Sep 15, 2022",
      title: "Ways To Choose Fruits & Seafoods For Pregnancy",
      description: "These are the people who make your life easier. Egestas is tristique vestibulum.",
      image: "/assets/blogs/blog1 (1).jpeg",
    },
    {
      id: 2,
      category: "Shopping",
      author: "Admin",
      date: "Sep 15, 2022",
      title: "Summer Breakfast With Tomatoes For Healthy ",
      description: "These are the people who make your life easier. Egestas is tristique vestibulum.",
      image: "/assets/blogs/blog1 (2).jpeg",
    },
    {
      id: 3,
      category: "Foods",
      author: "Admin",
      date: "Sep 15, 2022",
      title: "Popular Reasons You Should Drink Juice Every Day",
      description: "These are the people who make your life easier. Egestas is tristique vestibulum.",
      image: "/assets/blogs/blog1 (3).jpeg",
    },
    {
      id: 4,
      category: "Lifestyle",
      author: "Admin",
      date: "Sep 15, 2022",
      title: "Perfect Quality Products At Reasonable Family Prices",
      description: "These are the people who make your life easier. Egestas is tristique vestibulum.",
      image: "/assets/blogs/blog1 (4).jpeg",
    },
    {
      id: 5,
      category: "Foods",
      author: "Admin",
      date: "Sep 15, 2022",
      title: "Delicious Grilled Salmon Recipe With A Lemon Twist",
      description: "These are the people who make your life easier. Egestas is tristique vestibulum.",
      image: "/assets/blogs/blog1 (5).jpeg",
    },
    {
      id: 6,
      category: "Organics",
      author: "Admin",
      date: "Sep 15, 2022",
      title: "Fresh Seafood Platter For Memorable Occasions",
      description: "These are the people who make your life easier. Egestas is tristique vestibulum.",
      image: "/assets/blogs/blog1 (6).jpeg",
    },
    {
      id: 7,
      category: "Shopping",
      author: "Admin",
      date: "Sep 15, 2022",
      title: "Crispy Salad Recipes For A Healthy, Active Life",
      description: "These are the people who make your life easier. Egestas is tristique vestibulum.",
      image: "/assets/blogs/blog1 (7).jpeg",
    },
    {
      id: 8,
      category: "Foods",
      author: "Admin",
      date: "Sep 15, 2022",
      title: "Classic Steak Dinner Recipes Everyone Will Enjoy",
      description: "These are the people who make your life easier. Egestas is tristique vestibulum.",
      image: "/assets/blogs/blog1 (8).jpeg",
    },
  ];
  
  

  // ------------------------ testmonals ---------------
export const  Testimonials = [
  {
    name: "ALGISTINO LIONEL",
    position: "Web Designer at Blueskytechco",
    image: "/assets/imges/testmonals (1).png",
    rating: 5,
    review: "I think Hub is the best theme I ever seen this year. Amazing design, easy to customize and a design quality superlative account on its cloud platform for the optimized performance."
  },
  {
    name: "LEONARDO ROBEN",
    position: "Web Designer at Blueskytechco",
    image: "/assets/imges/testmonals (2).png",
    rating: 5,
    review: "I think Hub is the best theme I ever seen this year. Amazing design, easy to customize and a design quality superlative account on its cloud platform for the optimized performance."
  },
  {
    name: "ALGISTINO LIONEL",
    position: "Web Designer at Blueskytechco",
    image: "/assets/imges/testmonals (1).png",
    rating: 5,
    review: "I think Hub is the best theme I ever seen this year. Amazing design, easy to customize and a design quality superlative account on its cloud platform for the optimized performance."
  },
  {
    name: "LEONARDO ROBEN",
    position: "Web Designer at Blueskytechco",
    image: "/assets/imges/testmonals (2).png",
    rating: 5,
    review: "I think Hub is the best theme I ever seen this year. Amazing design, easy to customize and a design quality superlative account on its cloud platform for the optimized performance."
  },
  {
    name: "ALGISTINO LIONEL",
    position: "Web Designer at Blueskytechco",
    image: "/assets/imges/testmonals (1).png",
    rating: 5,
    review: "I think Hub is the best theme I ever seen this year. Amazing design, easy to customize and a design quality superlative account on its cloud platform for the optimized performance."
  },
  {
    name: "LEONARDO ROBEN",
    position: "Web Designer at Blueskytechco",
    image: "/assets/imges/testmonals (2).png",
    rating: 5,
    review: "I think Hub is the best theme I ever seen this year. Amazing design, easy to customize and a design quality superlative account on its cloud platform for the optimized performance."
  },
  {
    name: "ALGISTINO LIONEL",
    position: "Web Designer at Blueskytechco",
    image: "/assets/imges/testmonals (1).png",
    rating: 5,
    review: "I think Hub is the best theme I ever seen this year. Amazing design, easy to customize and a design quality superlative account on its cloud platform for the optimized performance."
  },
  {
    name: "LEONARDO ROBEN",
    position: "Web Designer at Blueskytechco",
    image: "/assets/imges/testmonals (2).png",
    rating: 5,
    review: "I think Hub is the best theme I ever seen this year. Amazing design, easy to customize and a design quality superlative account on its cloud platform for the optimized performance."
  },
  {
    name: "ALGISTINO LIONEL",
    position: "Web Designer at Blueskytechco",
    image: "/assets/imges/testmonals (1).png",
    rating: 5,
    review: "I think Hub is the best theme I ever seen this year. Amazing design, easy to customize and a design quality superlative account on its cloud platform for the optimized performance."
  },
  {
    name: "LEONARDO ROBEN",
    position: "Web Designer at Blueskytechco",
    image: "/assets/imges/testmonals (2).png",
    rating: 5,
    review: "I think Hub is the best theme I ever seen this year. Amazing design, easy to customize and a design quality superlative account on its cloud platform for the optimized performance."
  }
];
